version: '3.1'
services:
  ticketsales-mysql-db:
    image: 'mysql:8.0'
    container_name: 'mysql'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: 'always'
    environment:
      MYSQL_DATABASE: 'ticketsales'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: '30b3rb12cw'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
    - '3306:3306'
