package io.ticket.sales.api.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;

import javax.annotation.security.RolesAllowed;

import io.ticket.sales.api.controllers.entities.Ticket;
import io.ticket.sales.api.controllers.entities.TicketRepository;
import io.ticket.sales.config.GlobalConstants;


@EnableWebSecurity
@RestController
@RequestMapping("/feed")
public class FeedConroller {
    @Autowired // This means to get the bean called ticketRepository -- which is auto-generated by Spring, we will use it to handle the data
    private TicketRepository ticketRepository;

    @GetMapping
    @RolesAllowed({GlobalConstants.Roles.USER})
    public Iterable<Ticket> GetFeed(Integer userId) {
        if(userId != null) {
            return ticketRepository.findByCreatedByUserId(userId);
        }
        return new ArrayList<Ticket>();
    }

}
